In [1]:
import gymnasium as gym
import highway_env

env = gym.make("highway-fast-v0", render_mode="rgb_array")


In [2]:
obs, info = env.reset()
print(type(obs))
print(obs.shape)

<class 'numpy.ndarray'>
(5, 5)


In [3]:
obs

array([[ 1.        ,  0.74420226,  0.        ,  0.3125    ,  0.        ],
       [ 1.        ,  0.13081974,  0.6666667 , -0.02973626,  0.        ],
       [ 1.        ,  0.24494123,  0.6666667 , -0.03973628,  0.        ],
       [ 1.        ,  0.36940944,  0.6666667 , -0.02617779,  0.        ],
       [ 1.        ,  0.48016563,  0.6666667 , -0.03816779,  0.        ]],
      dtype=float32)

In [4]:
ego = obs[0]
ego

array([1.        , 0.74420226, 0.        , 0.3125    , 0.        ],
      dtype=float32)

In [5]:
obs.min(axis=0), obs.max(axis=0)

(array([ 1.        ,  0.13081974,  0.        , -0.03973628,  0.        ],
       dtype=float32),
 array([1.        , 0.74420226, 0.6666667 , 0.3125    , 0.        ],
       dtype=float32))

In [6]:
env.action_space

Discrete(5)

In [7]:
for a in range(env.action_space.n):
    print(a, env.unwrapped.action_type.actions[a])

0 LANE_LEFT
1 IDLE
2 LANE_RIGHT
3 FASTER
4 SLOWER


In [8]:
import numpy as np

env.reset()
for t in range(20):
    action = env.action_space.sample()
    obs, reward, terminated, truncated, info = env.step(action)
    print(f"t={t}, action={action}, reward={reward:.3f}")
    if terminated or truncated:
        break

t=0, action=4, reward=0.684
t=1, action=4, reward=0.669
t=2, action=2, reward=0.700
t=3, action=1, reward=0.700
t=4, action=1, reward=0.700
t=5, action=4, reward=0.700
t=6, action=0, reward=0.667
t=7, action=0, reward=0.667
t=8, action=2, reward=0.700
t=9, action=2, reward=0.733
t=10, action=1, reward=0.733
t=11, action=1, reward=0.733
t=12, action=1, reward=0.733
t=13, action=3, reward=0.849
t=14, action=4, reward=0.749
t=15, action=0, reward=0.701
t=16, action=4, reward=0.700
t=17, action=1, reward=0.700
t=18, action=0, reward=0.667
t=19, action=2, reward=0.700


In [9]:
env.unwrapped.config

{'observation': {'type': 'Kinematics'},
 'action': {'type': 'DiscreteMetaAction'},
 'simulation_frequency': 5,
 'policy_frequency': 1,
 'other_vehicles_type': 'highway_env.vehicle.behavior.IDMVehicle',
 'screen_width': 600,
 'screen_height': 150,
 'centering_position': [0.3, 0.5],
 'scaling': 5.5,
 'show_trajectories': False,
 'render_agent': True,
 'offscreen_rendering': False,
 'manual_control': False,
 'real_time_rendering': False,
 'lanes_count': 3,
 'vehicles_count': 20,
 'controlled_vehicles': 1,
 'initial_lane_id': None,
 'duration': 30,
 'ego_spacing': 1.5,
 'vehicles_density': 1,
 'collision_reward': -1,
 'right_lane_reward': 0.1,
 'high_speed_reward': 0.4,
 'lane_change_reward': 0,
 'reward_speed_range': [20, 30],
 'normalize_reward': True,
 'offroad_terminal': False}